version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  db:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: test2
    volumes:
      - db_test2:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: test2
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

volumes:
  db_test2:
